# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/WorkStations/ASIC/Whac-A-Mole/sim/SILENT/SILENT.srcs/sources_1/ip/MENUSCREEN/MENUSCREEN.xci
# IP: The module: 'MENUSCREEN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/SILENT/SILENT.gen/sources_1/ip/MENUSCREEN/MENUSCREEN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MENUSCREEN'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/WorkStations/ASIC/Whac-A-Mole/sim/SILENT/SILENT.srcs/sources_1/ip/MENUSCREEN/MENUSCREEN.xci
# IP: The module: 'MENUSCREEN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/SILENT/SILENT.gen/sources_1/ip/MENUSCREEN/MENUSCREEN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MENUSCREEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
