# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/WorkStations/ASIC/Whac-A-Mole/sim/BEEP/BEEP.srcs/sources_1/ip/BEEP_CLKMULT/BEEP_CLKMULT.xci
# IP: The module: 'BEEP_CLKMULT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/BEEP/BEEP.gen/sources_1/ip/BEEP_CLKMULT/BEEP_CLKMULT_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BEEP_CLKMULT'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/BEEP/BEEP.gen/sources_1/ip/BEEP_CLKMULT/BEEP_CLKMULT.xdc
# XDC: The top module name and the constraint reference have the same name: 'BEEP_CLKMULT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/BEEP/BEEP.gen/sources_1/ip/BEEP_CLKMULT/BEEP_CLKMULT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BEEP_CLKMULT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/WorkStations/ASIC/Whac-A-Mole/sim/BEEP/BEEP.srcs/sources_1/ip/BEEP_CLKMULT/BEEP_CLKMULT.xci
# IP: The module: 'BEEP_CLKMULT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/BEEP/BEEP.gen/sources_1/ip/BEEP_CLKMULT/BEEP_CLKMULT_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BEEP_CLKMULT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/BEEP/BEEP.gen/sources_1/ip/BEEP_CLKMULT/BEEP_CLKMULT.xdc
# XDC: The top module name and the constraint reference have the same name: 'BEEP_CLKMULT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/BEEP/BEEP.gen/sources_1/ip/BEEP_CLKMULT/BEEP_CLKMULT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BEEP_CLKMULT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
