# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/WorkStations/ASIC/Whac-A-Mole/sim/FINAL/FINAL.srcs/sources_1/ip/CLKWIZ/CLKWIZ.xci
# IP: The module: 'CLKWIZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/FINAL/FINAL.gen/sources_1/ip/CLKWIZ/CLKWIZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKWIZ'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/FINAL/FINAL.gen/sources_1/ip/CLKWIZ/CLKWIZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKWIZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/FINAL/FINAL.gen/sources_1/ip/CLKWIZ/CLKWIZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKWIZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/WorkStations/ASIC/Whac-A-Mole/sim/FINAL/FINAL.srcs/sources_1/ip/CLKWIZ/CLKWIZ.xci
# IP: The module: 'CLKWIZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/FINAL/FINAL.gen/sources_1/ip/CLKWIZ/CLKWIZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKWIZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/FINAL/FINAL.gen/sources_1/ip/CLKWIZ/CLKWIZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKWIZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/WorkStations/ASIC/Whac-A-Mole/sim/FINAL/FINAL.gen/sources_1/ip/CLKWIZ/CLKWIZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKWIZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
