# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/WorkStations/ASIC/Whac-A-Mole/constr/top_lcd_touch.xdc

# IP: ip/MOLESCREEN/MOLESCREEN.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MOLESCREEN || ORIG_REF_NAME==MOLESCREEN} -quiet] -quiet
